[project]
name = "GraphGen"
version = "0.1.0"
dependencies = [
    "requests>=2.31.0",
    "torch==2.6.0",
    "omegaconf",
    "numpy",
    "tqdm",
    "wandb",
    "pandas",
    "networkx",
    "matplotlib",
    "seaborn",
    "scipy",
    "PyQt5",
    "tensorboard",
    "tensorboardX",
    "tbparse",
    "bidict",
    "PrettyPrintTree",
    "pybind11",
]
requires-python = ">=3.10,<3.11"